# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetManager' do
  	pod 'Then'
	pod 'SnapKit'

end

target 'PetManagerTests' do
  	pod 'Then'
	pod 'SnapKit'
end